/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ApiHeader: typeof import('./src/components/common/api-header/api-header.vue')['default']
        DiffTable: typeof import('./src/components/common/diff-table/diff-table.vue')['default']
        DynamicTable: typeof import('./src/components/common/dynamic-table/dynamic-table.vue')['default']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElCol: typeof import('element-plus/es')['ElCol']
        ElContainer: typeof import('element-plus/es')['ElContainer']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElMenu: typeof import('element-plus/es')['ElMenu']
        ElOption: typeof import('element-plus/es')['ElOption']
        ElRow: typeof import('element-plus/es')['ElRow']
        ElSelect: typeof import('element-plus/es')['ElSelect']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        TablePreSave: typeof import('./src/components/settings/table-pre-save.vue')['default']
    }
}
